defaults :
  - modulus_default
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

arch:
  fully_connected:
    arch_type: fully_connected
    layer_size: 128
    nr_layers: 4

summary_histograms: true
jit: true
save_filetypes: "vtk"

optimizer:
  lr: 1e-3  # Increased learning rate

training:
  rec_results_freq: 500
  max_steps: 10000

batch_size:
  #Interior: 2048
  Interior: 4096
  #Interior_left: 2000
