defaults:
  - modulus_default
  - scheduler: tf_exponential_lr
  - optimizer: sgd
  - loss: sum
  - _self_

arch:
  fully_connected:
    arch_type: fully_connected
    layer_size: 128
    nr_layers: 4

summary_histograms: true
jit: true
save_filetypes: "vtk"

optimizer:
  lr: 1e-3
  momentum: 0.9

training:
  rec_results_freq: 500
  max_steps: 5000

batch_size:
  Refl_x: 200
  Refl_y: 200
  Trans_x: 200
  Trans_y: 200
  antenna_points: 500
  interior_air_nosource: 2500
  interior_concrete_nosource: 2500
